### ISSUE TITLE
Referencing file in local machine

### ISSUE THREAD

**Issue by zameel7** [Steffysomy/DEPdetection#1]
The code mentioned below is referencing file from the local disk on POST request. This might cause issue after hosting into production.

https://github.com/Steffysomy/DEPdetection/blob/a1c00f6db7b2d6e2ebe1ebe152a4e6f9b300b027/depApp/views.py#L152

Instead there are other ways to point towards the ```static``` folder.  Please update that.
@a1anjo

**Comment by a1anjo** [comment]
updated
